#ifndef ENCODEUTF_H
#define ENCODEUTF_H

#include "../includedefines/defines.h"
#include "../includedefines/inttypes.h"

#define C_CEDILLA 0xE7
#define C_CEDILLA_UPPERCASE 0xC7
#define A_TILDE 0xE3
#define A_TILDE_UPPERCASE 0xC3
#define O_TILDE 0xF5
#define O_TILDE_UPPERCASE 0xD5
#define A_CIRCUMFLEX 0xE2
#define A_CIRCUMFLEX_UPPERCASE 0xC2
#define O_CIRCUMFLEX 0xF4
#define O_CIRCUMFLEX_UPPERCASE 0xD4
#define E_CIRCUMFLEX 0xEA
#define E_CIRCUMFLEX_UPPERCASE 0xCA
#define I_CIRCUMFLEX 0xEE
#define I_CIRCUMFLEX_UPPERCASE 0xCE
#define U_CIRCUMFLEX 0xFB
#define U_CIRCUMFLEX_UPPERCASE 0xDB
#define A_ACUTE 0xE1
#define A_ACUTE_UPPERCASE 0xC1
#define O_ACUTE 0xF3
#define O_ACUTE_UPPERCASE 0xD3
#define E_ACUTE 0xE9
#define E_ACUTE_UPPERCASE 0xC9
#define I_ACUTE 0xED
#define I_ACUTE_UPPERCASE 0xCD
#define U_ACUTE 0xFA
#define U_ACUTE_UPPERCASE 0xDA
#define ACUTE_ACCENT 0xB4
#define GRAVE_ACCENT 0x60
#define CIRCUMFLEX_ACCENT 0x5E
#define TILDE 0x7E
#define DEGREE_SIGN 0xB0
#define MASCULINE_ORDINAL 0xBA
#define FEMININE_ORDINAL 0xAA
#define SECTION_SIGN 0xA7
#define SUPERSCRIPT_ONE 0xB9
#define SUPERSCRIPT_TWO 0xB2
#define SUPERSCRIPT_THREE 0xB3
#define POUND_STERLING 0xA3
#define CENT_SIGN 0xA2
#define NEGATION 0xAC

String GetUTF(String path, Byte *Error);

#endif //ENCODEUTF_H